## mvn -DskipTests package appengine:deploy

steps:
  # maven install
  - name: maven:3.8.3-openjdk-11-slim
    dir: ./crud
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  # build docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: ./crud
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/crud', '.' ]
  # push docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "push", "gcr.io/$PROJECT_ID/crud" ]
  # deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'beta', 'run', 'deploy', 'crud-application', '--cpu', '4', '--memory', '8Gi', '--timeout', '3600', '--concurrency', '1000', '--min-instances', '1', '--max-instances', '3',  '--platform', 'managed', '--ingress', 'all', '--allow-unauthenticated', '--no-cpu-throttling', '--image', 'gcr.io/$PROJECT_ID/crud', '--region', 'asia-southeast1']
images: [ 'gcr.io/$PROJECT_ID/crud' ]
