## mvn -DskipTests package appengine:deploy
steps:
#  # maven install
#  - name: maven:3.8.3-openjdk-11-slim
#    dir: ./crud
#    entrypoint: 'mvn'
#    args: ['clean', 'install', '-DskipTests']
#  # build docker image
#  - name: 'gcr.io/cloud-builders/docker'
#    dir: ./crud
#    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/crud', '.' ]
#  # push docker image
#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ "push", "gcr.io/$PROJECT_ID/crud" ]
  - id: 'Stage app using mvn appengine plugin'
    name: 'gcr.io/cloud-builders/mvn'
    args: [ 'DskipTests', 'package', 'appengine:deploy' ]
#  - id: 'Deploy to app engine'
#    name: 'gcr.io/cloud-builders/gcloud'
#    args: [ 'app', 'deploy', 'crud/appengine/app.yaml' ]

#  images: [ 'gcr.io/$PROJECT_ID/crud' ]

timeout: "1600s"
